# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


set(CPACK_ARCHIVE_COMPONENT_INSTALL "ON")
set(CPACK_ARCHIVE_GID "-1")
set(CPACK_ARCHIVE_PORTABLE_FILE_NAME "fng-0.6.5-win64")
set(CPACK_ARCHIVE_UID "-1")
set(CPACK_BUILD_SOURCE_DIRS "C:/Users/tailznic/Downloads/SNH;C:/Users/tailznic/Downloads/SNH/release")
set(CPACK_CMAKE_GENERATOR "Ninja")
set(CPACK_COMPONENTS_ALL "portable")
set(CPACK_COMPONENTS_ALL_SET_BY_USER "TRUE")
set(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
set(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_FILE "C:/msys64/mingw64/share/cmake/Templates/CPack.GenericDescription.txt")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_SUMMARY "fng built using CMake")
set(CPACK_GENERATOR "ZIP;TGZ;TBZ2;TXZ")
set(CPACK_IGNORE_FILES "\\.o$;\\.pyc$;/\\.git;/__pycache__/;C:/Users/tailznic/Downloads/SNH/([^Cbccdlorsss]|$);C:/Users/tailznic/Downloads/SNH/C([^M]|$);C:/Users/tailznic/Downloads/SNH/b([^a]|$);C:/Users/tailznic/Downloads/SNH/c([^mo]|$);C:/Users/tailznic/Downloads/SNH/d([^a]|$);C:/Users/tailznic/Downloads/SNH/l([^i]|$);C:/Users/tailznic/Downloads/SNH/o([^t]|$);C:/Users/tailznic/Downloads/SNH/r([^e]|$);C:/Users/tailznic/Downloads/SNH/s([^crt]|$);C:/Users/tailznic/Downloads/SNH/CM([^a]|$);C:/Users/tailznic/Downloads/SNH/ba([^m]|$);C:/Users/tailznic/Downloads/SNH/cm([^a]|$);C:/Users/tailznic/Downloads/SNH/co([^n]|$);C:/Users/tailznic/Downloads/SNH/da([^t]|$);C:/Users/tailznic/Downloads/SNH/li([^c]|$);C:/Users/tailznic/Downloads/SNH/ot([^h]|$);C:/Users/tailznic/Downloads/SNH/re([^a]|$);C:/Users/tailznic/Downloads/SNH/sc([^r]|$);C:/Users/tailznic/Downloads/SNH/sr([^c]|$);C:/Users/tailznic/Downloads/SNH/st([^o]|$);C:/Users/tailznic/Downloads/SNH/CMa([^k]|$);C:/Users/tailznic/Downloads/SNH/bam([^.]|$);C:/Users/tailznic/Downloads/SNH/cma([^k]|$);C:/Users/tailznic/Downloads/SNH/con([^f]|$);C:/Users/tailznic/Downloads/SNH/dat([^a]|$);C:/Users/tailznic/Downloads/SNH/lic([^e]|$);C:/Users/tailznic/Downloads/SNH/oth([^e]|$);C:/Users/tailznic/Downloads/SNH/rea([^d]|$);C:/Users/tailznic/Downloads/SNH/scr([^i]|$);C:/Users/tailznic/Downloads/SNH/src([^/]|$);C:/Users/tailznic/Downloads/SNH/sto([^r]|$);C:/Users/tailznic/Downloads/SNH/CMak([^e]|$);C:/Users/tailznic/Downloads/SNH/bam\\.([^l]|$);C:/Users/tailznic/Downloads/SNH/cmak([^e]|$);C:/Users/tailznic/Downloads/SNH/conf([^i]|$);C:/Users/tailznic/Downloads/SNH/data([^s]|$);C:/Users/tailznic/Downloads/SNH/lice([^n]|$);C:/Users/tailznic/Downloads/SNH/othe([^r]|$);C:/Users/tailznic/Downloads/SNH/read([^m]|$);C:/Users/tailznic/Downloads/SNH/scri([^p]|$);C:/Users/tailznic/Downloads/SNH/stor([^a]|$);C:/Users/tailznic/Downloads/SNH/CMake([^L]|$);C:/Users/tailznic/Downloads/SNH/bam\\.l([^u]|$);C:/Users/tailznic/Downloads/SNH/cmake([^/]|$);C:/Users/tailznic/Downloads/SNH/confi([^g]|$);C:/Users/tailznic/Downloads/SNH/datas([^r]|$);C:/Users/tailznic/Downloads/SNH/licen([^s]|$);C:/Users/tailznic/Downloads/SNH/other([^/]|$);C:/Users/tailznic/Downloads/SNH/readm([^e]|$);C:/Users/tailznic/Downloads/SNH/scrip([^t]|$);C:/Users/tailznic/Downloads/SNH/stora([^g]|$);C:/Users/tailznic/Downloads/SNH/CMakeL([^i]|$);C:/Users/tailznic/Downloads/SNH/bam\\.lu([^a]|$);C:/Users/tailznic/Downloads/SNH/config([^u]|$);C:/Users/tailznic/Downloads/SNH/datasr([^c]|$);C:/Users/tailznic/Downloads/SNH/licens([^e]|$);C:/Users/tailznic/Downloads/SNH/readme([^.]|$);C:/Users/tailznic/Downloads/SNH/script([^s]|$);C:/Users/tailznic/Downloads/SNH/storag([^e]|$);C:/Users/tailznic/Downloads/SNH/CMakeLi([^s]|$);C:/Users/tailznic/Downloads/SNH/configu([^r]|$);C:/Users/tailznic/Downloads/SNH/datasrc([^/]|$);C:/Users/tailznic/Downloads/SNH/license([^.]|$);C:/Users/tailznic/Downloads/SNH/readme\\.([^m]|$);C:/Users/tailznic/Downloads/SNH/scripts([^/]|$);C:/Users/tailznic/Downloads/SNH/storage([^.]|$);C:/Users/tailznic/Downloads/SNH/CMakeLis([^t]|$);C:/Users/tailznic/Downloads/SNH/configur([^e]|$);C:/Users/tailznic/Downloads/SNH/license\\.([^t]|$);C:/Users/tailznic/Downloads/SNH/readme\\.m([^d]|$);C:/Users/tailznic/Downloads/SNH/storage\\.([^c]|$);C:/Users/tailznic/Downloads/SNH/CMakeList([^s]|$);C:/Users/tailznic/Downloads/SNH/configure([^.]|$);C:/Users/tailznic/Downloads/SNH/license\\.t([^x]|$);C:/Users/tailznic/Downloads/SNH/storage\\.c([^f]|$);C:/Users/tailznic/Downloads/SNH/CMakeLists([^.]|$);C:/Users/tailznic/Downloads/SNH/configure\\.([^l]|$);C:/Users/tailznic/Downloads/SNH/license\\.tx([^t]|$);C:/Users/tailznic/Downloads/SNH/storage\\.cf([^g]|$);C:/Users/tailznic/Downloads/SNH/CMakeLists\\.([^t]|$);C:/Users/tailznic/Downloads/SNH/configure\\.l([^u]|$);C:/Users/tailznic/Downloads/SNH/CMakeLists\\.t([^x]|$);C:/Users/tailznic/Downloads/SNH/configure\\.lu([^a]|$);C:/Users/tailznic/Downloads/SNH/CMakeLists\\.tx([^t]|$)")
set(CPACK_INNOSETUP_ARCHITECTURE "x64")
set(CPACK_INSTALLED_DIRECTORIES "C:/Users/tailznic/Downloads/SNH;/")
set(CPACK_INSTALL_CMAKE_PROJECTS "")
set(CPACK_INSTALL_PREFIX "C:/Program Files (x86)/fng")
set(CPACK_MODULE_PATH "C:/Users/tailznic/Downloads/SNH/cmake")
set(CPACK_NSIS_DISPLAY_NAME "fng 0.6.5")
set(CPACK_NSIS_INSTALLER_ICON_CODE "")
set(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
set(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES64")
set(CPACK_NSIS_PACKAGE_NAME "fng 0.6.5")
set(CPACK_NSIS_UNINSTALL_NAME "Uninstall")
set(CPACK_OBJCOPY_EXECUTABLE "C:/msys64/mingw64/bin/objcopy.exe")
set(CPACK_OBJDUMP_EXECUTABLE "C:/msys64/mingw64/bin/objdump.exe")
set(CPACK_OUTPUT_CONFIG_FILE "C:/Users/tailznic/Downloads/SNH/release/CPackConfig.cmake")
set(CPACK_PACKAGE_DEFAULT_LOCATION "/")
set(CPACK_PACKAGE_DESCRIPTION_FILE "C:/msys64/mingw64/share/cmake/Templates/CPack.GenericDescription.txt")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "fng built using CMake")
set(CPACK_PACKAGE_FILE_NAME "fng-0.6.5-src")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "fng 0.6.5")
set(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "fng 0.6.5")
set(CPACK_PACKAGE_NAME "fng")
set(CPACK_PACKAGE_RELOCATABLE "true")
set(CPACK_PACKAGE_VENDOR "Humanity")
set(CPACK_PACKAGE_VERSION "0.6.5")
set(CPACK_PACKAGE_VERSION_MAJOR "0")
set(CPACK_PACKAGE_VERSION_MINOR "6")
set(CPACK_PACKAGE_VERSION_PATCH "5")
set(CPACK_READELF_EXECUTABLE "C:/msys64/mingw64/bin/readelf.exe")
set(CPACK_RESOURCE_FILE_LICENSE "C:/msys64/mingw64/share/cmake/Templates/CPack.GenericLicense.txt")
set(CPACK_RESOURCE_FILE_README "C:/msys64/mingw64/share/cmake/Templates/CPack.GenericDescription.txt")
set(CPACK_RESOURCE_FILE_WELCOME "C:/msys64/mingw64/share/cmake/Templates/CPack.GenericWelcome.txt")
set(CPACK_RPM_PACKAGE_SOURCES "ON")
set(CPACK_SET_DESTDIR "OFF")
set(CPACK_SOURCE_GENERATOR "ZIP;TGZ;TBZ2;TXZ")
set(CPACK_SOURCE_IGNORE_FILES "\\.o$;\\.pyc$;/\\.git;/__pycache__/;C:/Users/tailznic/Downloads/SNH/([^Cbccdlorsss]|$);C:/Users/tailznic/Downloads/SNH/C([^M]|$);C:/Users/tailznic/Downloads/SNH/b([^a]|$);C:/Users/tailznic/Downloads/SNH/c([^mo]|$);C:/Users/tailznic/Downloads/SNH/d([^a]|$);C:/Users/tailznic/Downloads/SNH/l([^i]|$);C:/Users/tailznic/Downloads/SNH/o([^t]|$);C:/Users/tailznic/Downloads/SNH/r([^e]|$);C:/Users/tailznic/Downloads/SNH/s([^crt]|$);C:/Users/tailznic/Downloads/SNH/CM([^a]|$);C:/Users/tailznic/Downloads/SNH/ba([^m]|$);C:/Users/tailznic/Downloads/SNH/cm([^a]|$);C:/Users/tailznic/Downloads/SNH/co([^n]|$);C:/Users/tailznic/Downloads/SNH/da([^t]|$);C:/Users/tailznic/Downloads/SNH/li([^c]|$);C:/Users/tailznic/Downloads/SNH/ot([^h]|$);C:/Users/tailznic/Downloads/SNH/re([^a]|$);C:/Users/tailznic/Downloads/SNH/sc([^r]|$);C:/Users/tailznic/Downloads/SNH/sr([^c]|$);C:/Users/tailznic/Downloads/SNH/st([^o]|$);C:/Users/tailznic/Downloads/SNH/CMa([^k]|$);C:/Users/tailznic/Downloads/SNH/bam([^.]|$);C:/Users/tailznic/Downloads/SNH/cma([^k]|$);C:/Users/tailznic/Downloads/SNH/con([^f]|$);C:/Users/tailznic/Downloads/SNH/dat([^a]|$);C:/Users/tailznic/Downloads/SNH/lic([^e]|$);C:/Users/tailznic/Downloads/SNH/oth([^e]|$);C:/Users/tailznic/Downloads/SNH/rea([^d]|$);C:/Users/tailznic/Downloads/SNH/scr([^i]|$);C:/Users/tailznic/Downloads/SNH/src([^/]|$);C:/Users/tailznic/Downloads/SNH/sto([^r]|$);C:/Users/tailznic/Downloads/SNH/CMak([^e]|$);C:/Users/tailznic/Downloads/SNH/bam\\.([^l]|$);C:/Users/tailznic/Downloads/SNH/cmak([^e]|$);C:/Users/tailznic/Downloads/SNH/conf([^i]|$);C:/Users/tailznic/Downloads/SNH/data([^s]|$);C:/Users/tailznic/Downloads/SNH/lice([^n]|$);C:/Users/tailznic/Downloads/SNH/othe([^r]|$);C:/Users/tailznic/Downloads/SNH/read([^m]|$);C:/Users/tailznic/Downloads/SNH/scri([^p]|$);C:/Users/tailznic/Downloads/SNH/stor([^a]|$);C:/Users/tailznic/Downloads/SNH/CMake([^L]|$);C:/Users/tailznic/Downloads/SNH/bam\\.l([^u]|$);C:/Users/tailznic/Downloads/SNH/cmake([^/]|$);C:/Users/tailznic/Downloads/SNH/confi([^g]|$);C:/Users/tailznic/Downloads/SNH/datas([^r]|$);C:/Users/tailznic/Downloads/SNH/licen([^s]|$);C:/Users/tailznic/Downloads/SNH/other([^/]|$);C:/Users/tailznic/Downloads/SNH/readm([^e]|$);C:/Users/tailznic/Downloads/SNH/scrip([^t]|$);C:/Users/tailznic/Downloads/SNH/stora([^g]|$);C:/Users/tailznic/Downloads/SNH/CMakeL([^i]|$);C:/Users/tailznic/Downloads/SNH/bam\\.lu([^a]|$);C:/Users/tailznic/Downloads/SNH/config([^u]|$);C:/Users/tailznic/Downloads/SNH/datasr([^c]|$);C:/Users/tailznic/Downloads/SNH/licens([^e]|$);C:/Users/tailznic/Downloads/SNH/readme([^.]|$);C:/Users/tailznic/Downloads/SNH/script([^s]|$);C:/Users/tailznic/Downloads/SNH/storag([^e]|$);C:/Users/tailznic/Downloads/SNH/CMakeLi([^s]|$);C:/Users/tailznic/Downloads/SNH/configu([^r]|$);C:/Users/tailznic/Downloads/SNH/datasrc([^/]|$);C:/Users/tailznic/Downloads/SNH/license([^.]|$);C:/Users/tailznic/Downloads/SNH/readme\\.([^m]|$);C:/Users/tailznic/Downloads/SNH/scripts([^/]|$);C:/Users/tailznic/Downloads/SNH/storage([^.]|$);C:/Users/tailznic/Downloads/SNH/CMakeLis([^t]|$);C:/Users/tailznic/Downloads/SNH/configur([^e]|$);C:/Users/tailznic/Downloads/SNH/license\\.([^t]|$);C:/Users/tailznic/Downloads/SNH/readme\\.m([^d]|$);C:/Users/tailznic/Downloads/SNH/storage\\.([^c]|$);C:/Users/tailznic/Downloads/SNH/CMakeList([^s]|$);C:/Users/tailznic/Downloads/SNH/configure([^.]|$);C:/Users/tailznic/Downloads/SNH/license\\.t([^x]|$);C:/Users/tailznic/Downloads/SNH/storage\\.c([^f]|$);C:/Users/tailznic/Downloads/SNH/CMakeLists([^.]|$);C:/Users/tailznic/Downloads/SNH/configure\\.([^l]|$);C:/Users/tailznic/Downloads/SNH/license\\.tx([^t]|$);C:/Users/tailznic/Downloads/SNH/storage\\.cf([^g]|$);C:/Users/tailznic/Downloads/SNH/CMakeLists\\.([^t]|$);C:/Users/tailznic/Downloads/SNH/configure\\.l([^u]|$);C:/Users/tailznic/Downloads/SNH/CMakeLists\\.t([^x]|$);C:/Users/tailznic/Downloads/SNH/configure\\.lu([^a]|$);C:/Users/tailznic/Downloads/SNH/CMakeLists\\.tx([^t]|$)")
set(CPACK_SOURCE_INSTALLED_DIRECTORIES "C:/Users/tailznic/Downloads/SNH;/")
set(CPACK_SOURCE_OUTPUT_CONFIG_FILE "C:/Users/tailznic/Downloads/SNH/release/CPackSourceConfig.cmake")
set(CPACK_SOURCE_PACKAGE_FILE_NAME "fng-0.6.5-src")
set(CPACK_SOURCE_TOPLEVEL_TAG "win64-Source")
set(CPACK_STRIP_FILES "")
set(CPACK_SYSTEM_NAME "win64")
set(CPACK_THREADS "1")
set(CPACK_TOPLEVEL_TAG "win64-Source")
set(CPACK_WIX_SIZEOF_VOID_P "8")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "C:/Users/tailznic/Downloads/SNH/release/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
